### ISSUE TITLE
producer.send occasionally fails with INVALID_RECORD

### ISSUE THREAD

**Issue by priitkaard** [priitkaard/kafka-ts#7]
Something in records is not always encoded correctly at the moment.

Error:

```
KafkaTSApiError: INVALID_RECORD\n    at /Users/sisu/Documents/kafkats/dist/api/produce.js:81:27\n    at Array.forEach (<anonymous>)\n    at /Users/sisu/Documents/kafkats/dist/api/produce.js:79:38\n    at Array.forEach (<anonymous>)\n    at Object.response (/Users/sisu/Documents/kafkats/dist/api/produce.js:78:26)\n    at Connection.sendRequest (/Users/sisu/Documents/kafkats/dist/connection.js:116:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /Users/sisu/Documents/kafkats/dist/producer/producer.js:88:24\n    at async Promise.all (index 0)\n    at async Producer.send (/Users/sisu/Documents/kafkats/dist/producer/producer.js:46:9)
```

Logs seen in kafka broker logs:

```
org.apache.kafka.common.InvalidRecordException: Found invalid number of record headers -27
{"level":"ERROR","timestamp":"2024-11-01 15:59:04,493","message":"[ReplicaManager broker=0] Error processing append operation on partition xxx","class":"kafka.server.ReplicaManager"}
```

```
org.apache.kafka.common.InvalidRecordException: Invalid negative header key size -62
{"level":"ERROR","timestamp":"2024-11-01 15:59:04,636","message":"[ReplicaManager broker=0] Error processing append operation on partition xxx","class":"kafka.server.ReplicaManager"}
```

**Comment by priit-sisutech** [comment]
solved by https://github.com/priitkaard/kafka-ts/commit/54c3dc7d7a83be1285a88439e59dbf9f82b8b7fb

VarLong/VarInt was encoded incorrectly.
